name: Update Site and Deploy to GitHub Pages

on:
  schedule:
    # 每天北京时间早上 9 点 (UTC 1点) 自动更新
    - cron: '0 1 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 更新网站内容
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Update last modified time
      run: |
        # 更新HTML中的时间戳
        current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
        echo "更新时间: $current_time"
        
        # 使用sed更新index.html中的时间
        sed -i "s|<p id=\"last-update\" class=\"last-update\">--</p>|<p id=\"last-update\" class=\"last-update\">$current_time</p>|g" index.html
        
        # 更新统计数据（模拟数据增长）
        # 活跃用户数增加随机数
        current_users=$(grep -o 'data-count="[0-9]*"' index.html | head -1 | grep -o '[0-9]*')
        new_users=$((current_users + $RANDOM % 1000 + 100))
        sed -i "s|data-count=\"$current_users\"|data-count=\"$new_users\"|" index.html
        
        # 对话次数增加随机数
        current_chats=$(grep -o 'data-count="[0-9]*"' index.html | sed -n '2p' | grep -o '[0-9]*')
        new_chats=$((current_chats + $RANDOM % 10000 + 1000))
        sed -i "s|data-count=\"$current_chats\"|data-count=\"$new_chats\"|2" index.html
        
        echo "统计数据已更新"
    
    - name: Update README timestamp only
      run: |
        # 只更新README中的时间戳，保留其他所有内容
        current_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')
        
        # 如果README包含更新时间行，则更新它
        if grep -q "**更新时间：" README.md; then
          sed -i "s|\*\*更新时间：.*\*\*|**更新时间：$(TZ='Asia/Shanghai' date '+%Y/%m/%d')**|g" README.md
          echo "README 时间戳已更新"
        else
          echo "README 不包含时间戳，跳过更新"
        fi
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "🤖 Auto-update: $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')"
          git push
          echo "Changes committed and pushed"
        else
          echo "No changes to commit"
        fi

  # 部署到 GitHub Pages
  deploy:
    needs: update-content
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main  # 确保获取最新的更改
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # 上传整个仓库
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 